common:
  request_headers:
    Accept: application/json
    Content-Type: application/json
sandbox:
  api_base_url: https://sandbox-nym-api1.nymtech.net/api/v1
  mix_id: 7
  identity_key: 2wEzyW6Pihk19xbCK9kB81vYuDFUvTzTAr77arvxdfSg
  gateway_identity: HjNEDJuotWV8VD4ufeA1jeheTnfNJ7Jorevp57hgaZua
  log_level: error
  time_zone: utc
prod:
  api_base_url: https://validator.nymtech.net/api/v1
  mix_id: 730
  mixnode_identity: 3pMCJswCyA19MGYWGDWT5fBk2M8ybSZGXttyAoNY5gBB
  gateway_identity: 2BuMSfMW3zpeAjKXyKLhmY4QW1DXurrtSPEJ6CjX3SEh
  log_level: error
  time_zone: utc